### ISSUE TITLE
Frodo is missing as a Passenger option for Awen in Road to Rivendell

### ISSUE THREAD

**Issue by avcordaro** [avcordaro/mesbg-list-builder-v2024#76]
Feedback reported from user:

In the Road to Rivendell list, Arwen does not have the ability to add Frodo as a passenger via a wargear toggle the same way as Gandalf or Eowyn. This should be added since the army may chose to use Frodo as a passenger, but it is not mandatory, so there needs to be a way to differentiate those situations.

**Comment by mhollink** [comment]
While we were implementing a toggle on Arwen we noticed a lot of small little problems. For example, if you have added Frodo as a passenger you will be unable to add his wargear options (Sting & the Mithril Coat). 

Since the rule starts with "If your Army includes both Frodo and Arwen, then Frodo may begin the game as a Passenger upon Asfaloth" we decided to leave it up to the player to either add him on the back of Asfaloth, or not.

Including Frodo as a normal unit (probably in the same warband as Arwen) also automatically resolves any issues such as the MWF totals, the Resistant to magic highlighting as well as some issues it would give us in the PDF export.
